name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-dash-app .
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'
    

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "gcr.io"

      - name: Push Docker image to Artifact Registry
        run: |
          docker tag my-dash-app gcr.io/my-dash-app-1-421618/dash-app/my-dash-app
          docker push gcr.io/my-dash-app-1-421618/dash-app/my-dash-app

      - name: Deploy to GCP Cloud Run
        run: |
          gcloud run deploy my-dash-app --region us-central1 --image "gcr.io/my-dash-app-1-421618/dash-app/my-dash-app" --platform managed
